// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4W06b7aZprrcF_hG1vOI1mJXaImGCsQk',
    appId: '1:244097271197:android:e6a7d851db424c37e99b74',
    messagingSenderId: '244097271197',
    projectId: 'we-chat-f74f6',
    storageBucket: 'we-chat-f74f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iVran6z3mKXrZdB-WzHA32JC9W52lFY',
    appId: '1:244097271197:ios:78e20f0c5a9592bfe99b74',
    messagingSenderId: '244097271197',
    projectId: 'we-chat-f74f6',
    storageBucket: 'we-chat-f74f6.appspot.com',
    androidClientId: '244097271197-opesed09u0vd0sjc9sfliicd1ol328bm.apps.googleusercontent.com',
    iosClientId: '244097271197-sebvuva3otm3at3k35cd5pol523hosj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatfirebase',
  );
}
